import SoilHealthCard from "./SoilHealthCard";
import BestCropCard from "./BestCropCard";
import DeficiencyCard from "./DeficiencyCard";
import SoilManagementCard from "./SoilManagementCard";
import AISummaryCard from "./AISummaryCard";
import NutrientChart from "./NutrientChart";
import CropRankingTable from "./CropRankingTable";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
} from "recharts";
import jsPDF from "jspdf";
import SoilHealthGauge from "./SoilHealthGauge";
import { translations } from "../services/translations";
import "./Dashboard.css";

function Dashboard({ analysis, rankings, setView, language }) {
  const t = translations[language] || translations["English"];
  console.log("Analysis Data:", analysis);
  if (!analysis) {
    return <h2>No analysis data available.</h2>;
  }
  console.log("ANALYSIS DATA:", analysis);
  const cropTranslationMap = {
    "Wheat": { Hindi: "गेहूँ", Marathi: "गेहूँ", Gujarati: "ઘઉં" },
    "Rice": { Hindi: "धान", Marathi: "तांदूळ", Gujarati: "ડાંગર" },
    "Maize": { Hindi: "मक्का", Marathi: "मका", Gujarati: "મકાઈ" },
    "Soybean": { Hindi: "सोयाबीन", Marathi: "सोयाबीन", Gujarati: "સોયાબીન" },
    "Cotton": { Hindi: "कपास", Marathi: "कापूस", Gujarati: "કપાસ" },
    "Groundnut": { Hindi: "मूंगफली", Marathi: "भुईमूग", Gujarati: "મગફળી" },
    "Sugarcane": { Hindi: "गन्ना", Marathi: "ऊस", Gujarati: "શેરડી" },
    "Tomato": { Hindi: "टमाटर", Marathi: "टोमॅटो", Gujarati: "ટોમેટો" },
    "Potato": { Hindi: "आलू", Marathi: "बटाटा", Gujarati: "બટાકા" },
    "Onion": { Hindi: "प्याज", Marathi: "कांदा", Gujarati: "ડુંગળી" },
  };

  const getTranslatedCropName = (cropName) => {
    if (language === "English") return cropName;
    return cropTranslationMap[cropName]?.[language] || cropName;
  };

  const npkData = [
    {
      name:
        language === "Hindi"
          ? "नाइट्रोजन"
          : language === "Marathi"
          ? "नायट्रोजन"
          : language === "Gujarati"
          ? "નાઇટ્રોજન"
          : "Nitrogen",
      value: analysis.N || 0,
    },
    {
      name:
        language === "Hindi"
          ? "फास्फोरस"
          : language === "Marathi"
          ? "फॉस्फरस"
          : language === "Gujarati"
          ? "ફોસ્ફરસ"
          : "Phosphorus",
      value: analysis.P || 0,
    },
    {
      name:
        language === "Hindi"
          ? "पोटेशियम"
          : language === "Marathi"
          ? "पोटॅशियम"
          : language === "Gujarati"
          ? "પોટેશિયમ"
          : "Potassium",
      value: analysis.K || 0,
    },
  ];

  const cropData =
    rankings?.slice(0, 5).map((crop) => ({
      crop: getTranslatedCropName(crop.crop),
      score: crop.score,
    })) || [];
  const downloadReport = () => {
    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.text("AI Soil Health Analysis Report", 20, 20);

    doc.setFontSize(12);

    doc.text(`Soil Health Score: ${analysis.soil_health_score}/100`, 20, 40);

    doc.text(`Soil Status: ${analysis.soil_health_status}`, 20, 50);

    doc.text(`Recommended Crop: ${analysis.recommended_crop}`, 20, 60);

    doc.text(`pH: ${analysis.ph}`, 20, 70);

    doc.text(`Nitrogen: ${analysis.N}`, 20, 80);

    doc.text(`Phosphorus: ${analysis.P}`, 20, 90);

    doc.text(`Potassium: ${analysis.K}`, 20, 100);

    doc.text(
      `Deficiencies: ${analysis.deficiencies.join(", ") || "None"}`,
      20,
      120,
    );

    doc.text(
      `Fertilizers: ${
        analysis.fertilizer_recommendations.join(", ") || "None"
      }`,
      20,
      135,
    );

    doc.text(`Generated by AI Soil Health Advisory System`, 20, 260);

    doc.save("soil-report.pdf");
  };
  const statusMap = {
    Excellent: { English: "Excellent", Hindi: "उत्कृष्ट", Marathi: "उत्कृष्ट", Gujarati: "ઉત્કૃષ્ટ" },
    Good: { English: "Good", Hindi: "अच्छा", Marathi: "चांगले", Gujarati: "સારું" },
    Moderate: { English: "Moderate", Hindi: "मध्यम", Marathi: "मध्यम", Gujarati: "મધ્યમ" },
    Poor: { English: "Poor", Hindi: "खराब", Marathi: "खराब", Gujarati: "ખરાબ" },
  };

  const getTranslatedStatus = (status) => {
    return statusMap[status]?.[language] || status;
  };

  return (
    <div className="dashboard-container">
      <div className="dashboard-header">
        <h1>{t.dashHeaderTitle}</h1>
        <p>{t.dashHeaderSub}</p>
      </div>
      <div className="stats-row">
        <div className="stat-card soil-health-card">
          <h3>{t.dashSoilHealth}</h3>
          <h2>{analysis.soil_health_score}/100</h2>

          <span className="status-badge">
            {getTranslatedStatus(analysis.soil_health_status)}
          </span>
        </div>

        <div className="stat-card best-crop-card">
          <h3>{t.dashRecCrop}</h3>
          <h2>{getTranslatedCropName(rankings?.[0]?.crop || analysis.recommended_crop)}</h2>
          <p>{t.dashBasedOn}</p>
        </div>
    
      </div>
      <button onClick={downloadReport} className="download-btn">
        {t.dashDownload}
      </button>
      <div className="dashboard-grid">
        <SoilHealthCard
          score={analysis.soil_health_score}
          status={getTranslatedStatus(analysis.soil_health_status)}
        />
        <div className="card">
          <h2>{t.dashTopCrops}</h2>

          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={cropData}>
              <XAxis dataKey="crop" />
              <YAxis />
              <Tooltip />
              <Bar dataKey="score" fill="#2d6a4f" />
            </BarChart>
          </ResponsiveContainer>
        </div>
        <div className="card">
          <h2>{t.dashNpkAnalysis}</h2>

          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={npkData}>
              <XAxis dataKey="name" />
              <YAxis />
              <Tooltip />
              <Bar dataKey="value" fill="#e9c46a" />
            </BarChart>
          </ResponsiveContainer>
        </div>
        <SoilHealthGauge
          score={analysis.soil_health_score}
          status={getTranslatedStatus(analysis.soil_health_status)}
        />

        <BestCropCard
          crop={getTranslatedCropName(rankings?.[0]?.crop || analysis.recommended_crop)}
          score={rankings?.[0]?.score || 0}
        />

        <DeficiencyCard deficiencies={analysis.deficiencies || []} />

        <SoilManagementCard recommendations={analysis.improvement_plan || []} />
      </div>

      <AISummaryCard summary={analysis.ai_summary} language={language} />

      <div style={{ marginTop: "20px" }}>
        <NutrientChart
          N={analysis.N || 0}
          P={analysis.P || 0}
          K={analysis.K || 0}
          ph={analysis.ph || 0}
        />
      </div>

      <div style={{ marginTop: "20px" }}>
        <CropRankingTable crops={rankings || []} />
      </div>
      <button
        onClick={() => setView("form")}
        className="download-btn"
      >
        {t.dashAnalyzeAnother}
      </button>
      <button onClick={() => setView("chat")} className="chat-btn">
        {t.dashAskKisan}
      </button>
    </div>
  );
}

export default Dashboard;
