import SoilHealthCard from "./SoilHealthCard";
import BestCropCard from "./BestCropCard";
import DeficiencyCard from "./DeficiencyCard";
import SoilManagementCard from "./SoilManagementCard";
import AISummaryCard from "./AISummaryCard";
import NutrientChart from "./NutrientChart";
import CropRankingTable from "./CropRankingTable";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
} from "recharts";
import jsPDF from "jspdf";
function Dashboard({ analysis, rankings, setView }) {
  console.log("Analysis Data:", analysis);
  if (!analysis) {
    return <h2>No analysis data available.</h2>;
  }
  const npkData = [
    { name: "Nitrogen", value: analysis.N || 0 },
    { name: "Phosphorus", value: analysis.P || 0 },
    { name: "Potassium", value: analysis.K || 0 },
  ];
  const soilHealthData = [
    {
      name: "Healthy",
      value: analysis.soil_health_score,
    },
    {
      name: "Needs Improvement",
      value: 100 - analysis.soil_health_score,
    },
  ];
  const cropData =
    rankings?.slice(0, 5).map((crop) => ({
      crop: crop.crop,
      score: crop.score,
    })) || [];
  const downloadReport = () => {
    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.text("AI Soil Health Analysis Report", 20, 20);

    doc.setFontSize(12);

    doc.text(`Soil Health Score: ${analysis.soil_health_score}/100`, 20, 40);

    doc.text(`Soil Status: ${analysis.soil_health_status}`, 20, 50);

    doc.text(`Recommended Crop: ${analysis.crop}`, 20, 60);

    doc.text(`pH: ${analysis.ph}`, 20, 70);

    doc.text(`Nitrogen: ${analysis.N}`, 20, 80);

    doc.text(`Phosphorus: ${analysis.P}`, 20, 90);

    doc.text(`Potassium: ${analysis.K}`, 20, 100);

    doc.text(
      `Deficiencies: ${analysis.deficiencies.join(", ") || "None"}`,
      20,
      120,
    );

    doc.text(
      `Fertilizers: ${
        analysis.fertilizer_recommendations.join(", ") || "None"
      }`,
      20,
      135,
    );

    doc.text(`Generated by AI Soil Health Advisory System`, 20, 260);

    doc.save("soil-report.pdf");
  };
  return (
    <div className="dashboard-container">
      <div className="dashboard-header">
        <h1>🌱 AI Soil Health Dashboard</h1>
        <p>Smart Soil Analysis • Crop Recommendation • AI Advisory</p>
      </div>
      <div className="stats-row">
        <div className="stat-card">
          <h3>🌱 Soil Health</h3>
          <h2>{analysis.soil_health_score}/100</h2>
        </div>

        <div className="stat-card">
          <h3>🏆 Best Crop</h3>
          <h2>{analysis.crop}</h2>
        </div>

        <div className="stat-card">
          <h3>⚠ Deficiencies</h3>
          <h2>{analysis.deficiencies?.length || 0}</h2>
        </div>
      </div>
      <button onClick={downloadReport} className="download-btn">
        📄 Download Soil Report
      </button>
      <div className="dashboard-grid">
        <SoilHealthCard
          score={analysis.soil_health_score}
          status={analysis.soil_health_status}
        />
        <div className="card">
          <h2>Top Crop Recommendations</h2>

          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={cropData}>
              <XAxis dataKey="crop" />
              <YAxis />
              <Tooltip />
              <Bar dataKey="score" fill="#2d6a4f" />
            </BarChart>
          </ResponsiveContainer>
        </div>
        <div className="card">
          <h2>NPK Analysis</h2>

          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={npkData}>
              <XAxis dataKey="name" />
              <YAxis />
              <Tooltip />
              <Bar dataKey="value" fill="#e9c46a" />
            </BarChart>
          </ResponsiveContainer>
        </div>
        <div className="card">
          <h2>Soil Health Score</h2>

          <ResponsiveContainer width="100%" height={250}>
            <PieChart>
              <Pie
  data={soilHealthData}
  dataKey="value"
  nameKey="name"
  outerRadius={80}
  label
>
  <Cell fill="#2d6a4f" />
  <Cell fill="#d9d9d9" />
</Pie>
              <Tooltip />
            </PieChart>
          </ResponsiveContainer>

          <p>Current Score: {analysis.soil_health_score}/100</p>
        </div>

        <BestCropCard crop={analysis.crop} score={rankings?.[0]?.score || 0} />

        <DeficiencyCard deficiencies={analysis.deficiencies || []} />

        <SoilManagementCard recommendations={analysis.improvement_plan || []} />
      </div>

      <AISummaryCard summary={analysis.ai_summary} />

      <div style={{ marginTop: "20px" }}>
        <NutrientChart
          N={analysis.N || 0}
          P={analysis.P || 0}
          K={analysis.K || 0}
          ph={analysis.ph || 0}
        />
      </div>

      <div style={{ marginTop: "20px" }}>
        <CropRankingTable crops={rankings || []} />
      </div>

      <button onClick={() => setView("chat")} className="chat-btn">
        🤖 Ask KisanBot
      </button>
    </div>
  );
}

export default Dashboard;
