import SoilHealthCard from "./SoilHealthCard";
import BestCropCard from "./BestCropCard";
import DeficiencyCard from "./DeficiencyCard";
import SoilManagementCard from "./SoilManagementCard";
import AISummaryCard from "./AISummaryCard";
import NutrientChart from "./NutrientChart";
import CropRankingTable from "./CropRankingTable";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
} from "recharts";
import jsPDF from "jspdf";
import SoilHealthGauge from "./SoilHealthGauge";
import { translations } from "../services/translations";
import "./Dashboard.css";

function Dashboard({ analysis, rankings, setView, language }) {
  const t = translations[language] || translations["English"];
  console.log("Analysis Data:", analysis);
  if (!analysis) {
    return <h2>No analysis data available.</h2>;
  }
  console.log("ANALYSIS DATA:", analysis);
  const cropTranslationMap = {
    "Wheat": { Hindi: "गेहूँ", Marathi: "गेहूँ", Gujarati: "ઘઉં" },
    "Rice": { Hindi: "धान", Marathi: "तांदूळ", Gujarati: "ડાંગર" },
    "Maize": { Hindi: "मक्का", Marathi: "मका", Gujarati: "મકાઈ" },
    "Soybean": { Hindi: "सोयाबीन", Marathi: "सोयाबीन", Gujarati: "સોયાબીન" },
    "Cotton": { Hindi: "कपास", Marathi: "कापूस", Gujarati: "કપાસ" },
    "Groundnut": { Hindi: "मूंगफली", Marathi: "भुईमूग", Gujarati: "મગફળી" },
    "Sugarcane": { Hindi: "गन्ना", Marathi: "ऊस", Gujarati: "શેરડી" },
    "Tomato": { Hindi: "टमाटर", Marathi: "टोमॅटो", Gujarati: "ટોમેટો" },
    "Potato": { Hindi: "आलू", Marathi: "बटाटा", Gujarati: "બટાકા" },
    "Onion": { Hindi: "प्याज", Marathi: "कांदा", Gujarati: "ડુંગળી" },
  };

  const getTranslatedCropName = (cropName) => {
    if (language === "English") return cropName;
    return cropTranslationMap[cropName]?.[language] || cropName;
  };

  const cropData =
    rankings?.slice(0, 5).map((crop) => ({
      crop: getTranslatedCropName(crop.crop),
      score: crop.score,
    })) || [];

  const downloadReport = () => {
    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.text("AI Soil Health Analysis Report", 20, 20);

    doc.setFontSize(12);

    doc.text(`Soil Health Score: ${analysis.soil_health_score}/100`, 20, 40);

    doc.text(`Soil Status: ${analysis.soil_health_status}`, 20, 50);

    doc.text(`Recommended Crop: ${analysis.recommended_crop}`, 20, 60);

    doc.text(`pH: ${analysis.ph}`, 20, 70);

    doc.text(`Nitrogen: ${analysis.N}`, 20, 80);

    doc.text(`Phosphorus: ${analysis.P}`, 20, 90);

    doc.text(`Potassium: ${analysis.K}`, 20, 100);

    doc.text(
      `Deficiencies: ${analysis.deficiencies.join(", ") || "None"}`,
      20,
      120,
    );

    doc.text(
      `Fertilizers: ${
        analysis.fertilizer_recommendations.join(", ") || "None"
      }`,
      20,
      135,
    );

    doc.text(`Generated by AI Soil Health Advisory System`, 20, 260);

    doc.save("soil-report.pdf");
  };

  const statusMap = {
    Excellent: { English: "Excellent", Hindi: "उत्कृष्ट", Marathi: "उत्कृष्ट", Gujarati: "ઉત્કૃષ્ટ" },
    Good: { English: "Good", Hindi: "अच्छा", Marathi: "चांगले", Gujarati: "સારું" },
    Moderate: { English: "Moderate", Hindi: "मध्यम", Marathi: "मध्यम", Gujarati: "મધ્યમ" },
    Poor: { English: "Poor", Hindi: "खराब", Marathi: "खराब", Gujarati: "ખરાબ" },
  };

  const getTranslatedStatus = (status) => {
    return statusMap[status]?.[language] || status;
  };

  return (
    <div className="dashboard-container">
      <div className="dashboard-header">
        <h1>{t.dashHeaderTitle}</h1>
        <p>{t.dashHeaderSub}</p>
      </div>

      <div className="stats-row">
        <div className="stat-card soil-health-card">
          <h3>{t.dashSoilHealth}</h3>
          <h2>{analysis.soil_health_score}/100</h2>

          <span className="status-badge">
            {getTranslatedStatus(analysis.soil_health_status)}
          </span>
        </div>

        <div className="stat-card best-crop-card">
          <h3>{t.dashRecCrop}</h3>
          <h2>{getTranslatedCropName(analysis.recommended_crop)}</h2>
          <p>{t.dashBasedOn}</p>
        </div>
      </div>

      <button onClick={downloadReport} className="download-btn">
        {t.dashDownload}
      </button>

      <div className="dashboard-grid">
        {/* ROW 1: Soil Health Indicator and Recommended/Alternative Crops */}
        <SoilHealthGauge
          score={analysis.soil_health_score}
          status={getTranslatedStatus(analysis.soil_health_status)}
        />

        <div style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
          <BestCropCard
            title={language === "Hindi" ? "🏆 अनुशंसित फसल (ML)" : language === "Marathi" ? "🏆 शिफारस केलेले पीक (ML)" : language === "Gujarati" ? "🏆 ભલામણ કરેલ પાક (ML)" : "🏆 Recommended Crop (ML)"}
            crop={getTranslatedCropName(analysis.recommended_crop)}
            rawCropName={analysis.recommended_crop}
            score={rankings?.find(r => r.crop.toLowerCase() === analysis.recommended_crop?.toLowerCase())?.score || rankings?.[0]?.score || 0}
            subtitle={language === "Hindi" ? "मशीन लर्निंग मॉडल द्वारा मिट्टी और मौसम के मानदंडों का उपयोग करके अनुमानित फसल।" : language === "Marathi" ? "माती आणि हवामानाच्या निकषांचा वापर करून मशीन लर्निंग मॉडेलद्वारे अंदाजित पीक." : language === "Gujarati" ? "મશીન લર્નિંગ મોડલ દ્વારા માટી અને હવામાનના પરિમાણોનો ઉપયોગ કરીને અનુમાનિત પાક." : "Most suitable crop predicted by Machine Learning model using soil and weather parameters."}
          />
          <BestCropCard
            title={language === "Hindi" ? "🌾 वैकल्पिक फसल (नियम इंजन)" : language === "Marathi" ? "🌾 पर्यायी पीक (नियम इंजिन)" : language === "Gujarati" ? "🌾 વૈકલ્પિક પાક (નિયમ એન્જિન)" : "🌾 Alternative Crop (Rule Engine)"}
            crop={getTranslatedCropName(analysis.alternative_crop)}
            rawCropName={analysis.alternative_crop}
            score={rankings?.find(r => r.crop.toLowerCase() === analysis.alternative_crop?.toLowerCase())?.score || rankings?.[1]?.score || 0}
            icon="🌱"
            subtitle={language === "Hindi" ? "एनपीके और पीएच सीमाओं के आधार पर नियम इंजन द्वारा सुझाई गई वैकल्पिक फसल।" : language === "Marathi" ? "एनपीके आणि पीएच मर्यादांवर आधारित नियम इंजिनद्वारे सुचविलेले पर्यायी पीक." : language === "Gujarati" ? "NPK અને pH મર્યાદાના આધारे નિયમ એન્જિન દ્વારા સૂચવવામાં આવેલ વૈકલ્પિક પાક." : "Alternative crop recommendation computed by the rule-engine based on NPK & pH thresholds."}
          />
        </div>

        {/* ROW 2: Crop Recommendations Chart & Nutrient Analysis Chart */}
        <div className="card">
          <h2>{t.dashTopCrops}</h2>
          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={cropData}>
              <XAxis dataKey="crop" />
              <YAxis />
              <Tooltip />
              <Bar dataKey="score" fill="#2d6a4f" />
            </BarChart>
          </ResponsiveContainer>
        </div>

        <NutrientChart
          N={analysis.N || 0}
          P={analysis.P || 0}
          K={analysis.K || 0}
          ph={analysis.ph || 0}
        />

        {/* ROW 3: Deficiencies and Improvement Plans */}
        <DeficiencyCard deficiencies={analysis.deficiencies || []} />

        <SoilManagementCard recommendations={analysis.improvement_plan || []} />
      </div>

      <AISummaryCard summary={analysis.ai_summary} language={language} />

      <div style={{ marginTop: "20px" }}>
        <CropRankingTable crops={rankings || []} />
      </div>

      <div className="dashboard-action-buttons" style={{ display: "flex", gap: "20px", justifyContent: "center", marginTop: "30px" }}>
        <button
          onClick={() => setView("form")}
          className="download-btn"
          style={{ margin: "0" }}
        >
          {t.dashAnalyzeAnother}
        </button>
        <button onClick={() => setView("chat")} className="chat-btn" style={{ margin: "0" }}>
          {t.dashAskKisan}
        </button>
      </div>
    </div>
  );
}

export default Dashboard;
